# Generated by Django 4.2.2 on 2023-06-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_person_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
