# Generated by Django 4.2.2 on 2023-06-13 21:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_alter_post_desc_alter_profile_pic_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='desc',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
