# Generated by Django 4.2.2 on 2023-06-13 23:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_alter_comment_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
